services:
  frontend:
    image: yahkerobertkertasnya/splanngo-fe:latest
    tty: true
    build: .
    networks:
      - splanngo
    ports:
      - "3646:3000"
    environment:
      - NEXT_PUBLIC_IS_CONTAINER=true
      - NEXT_PUBLIC_BACKEND_DOCKER_URL=${NEXT_PUBLIC_BACKEND_DOCKER_URL}
      - NEXT_PUBLIC_BACKEND_URL=${NEXT_PUBLIC_BACKEND_URL}
      - NEXTAUTH_SECRET=${NEXTAUTH_SECRET}
      - NEXTAUTH_URL=${NEXTAUTH_URL}
    restart: on-failure


networks:
  splanngo:
    external: true