services:
  frontend:
    image: yahkerobertkertasnya/splanngo-fe:latest
    tty: true
    build: .
    ports:
      - "3646:3000"
    environment:
      - NEXT_PUBLIC_BACKEND_URL=${NEXT_PUBLIC_BACKEND_URL}
      - NEXTAUTH_SECRET=${NEXTAUTH_SECRET}
    restart: on-failure
